/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mycompany_package1_HelloWorld */

#ifndef _Included_com_mycompany_package1_HelloWorld
#define _Included_com_mycompany_package1_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mycompany_package1_HelloWorld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mycompany_package1_HelloWorld_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
